# Generated by Django 4.2.16 on 2025-02-02 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_desc_contact_message_remove_contact_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
